stages:
  - test
  - build
  - deploy

variables:
  OKD_REGISTRY: "image-registry.apps.private.okd4.teh-1.cloud.io"
  OKD_URL: "https://api.okd4.teh-1.cloud.io:6443"
  OKD_PROJECT_NAME: "skype-notifier-dpn"

test: 
  image: sourabh385/helm-oc-cli:latest
  stage: test
  script:
    - oc login --token=${OKD_TOKEN} --server=${OKD_URL}
    - oc project ${OKD_PROJECT_NAME}
    - helm install --dry-run skype-notifier helm 

build-okd-registry:
  image: docker:19.03.12
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
    CONTAINER_REGISTRY_ADDRESS: "$OKD_REGISTRY"
    CONTAINER_REGISTRY_IMAGE: "$OKD_REGISTRY/$OKD_PROJECT_NAME/$CI_PROJECT_NAME"
    CONTAINER_REGISTRY_IMAGE_TAG: "1.0.2"
    CONTAINER_REGISTRY_USERNAME: "gitlab-ci"
    CONTAINER_REGISTRY_PASSWORD: ${OKD_TOKEN}

  script:
    - docker login -u ${CONTAINER_REGISTRY_USERNAME} -p ${CONTAINER_REGISTRY_PASSWORD} ${CONTAINER_REGISTRY_ADDRESS}
    - docker build -t ${CONTAINER_REGISTRY_IMAGE}:${CONTAINER_REGISTRY_IMAGE_TAG} .
    - docker push ${CONTAINER_REGISTRY_IMAGE}:${CONTAINER_REGISTRY_IMAGE_TAG}

  dependencies:
    - test

deploy: 
  image: sourabh385/helm-oc-cli:latest
  stage: deploy
  script:
    - oc login --token=${OKD_TOKEN} --server=${OKD_URL}
    - oc project ${OKD_PROJECT_NAME}
    - helm upgrade --install skype-notifier helm 

  dependencies:
    - build-okd-registry