version: "3"
services:
  web:
    env_file:
      - docker/.env
    container_name: skype_notifier
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "7654:8080"
    restart: always
    dns:
      - 8.8.8.8
